kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: '2022-09-28T04:49:33Z'
  name: minio

  labels:
    app: minio
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio-app
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: 'quay.io/minio/minio:latest'
      from:
        kind: DockerImage
        name: 'quay.io/minio/minio:latest'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
