apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#bases:
#- ../../base


resources: 
- deploymentconfig-minio.yaml 
- imagestream-minio.yaml 
- persistentvolumeclaim-minio.yaml 
- route-minio-console.yaml 
- route-minio.yaml 
- service-minio-console.yaml 
- service-minio.yaml